In [1]:
import numpy as np
import numpy.typing as npt
from disjoint_set import DisjointSet

NDArrayInt = npt.NDArray[np.int_]
NDArrayFloat = npt.NDArray[np.float_]

import graphblas as gb
import networkx as nx
from scipy.sparse import *
from scipy.sparse.csgraph import floyd_warshall

In [7]:
graph = random(5, 5, density=0.25, data_rvs=np.ones).astype(np.int_)

gb_graph = gb.io.from_scipy_sparse(graph)
print(gb_graph)

C(gb.op.min) << gb.semiring.min_plus(gb_graph @ gb_graph)
print(C)

def gb_shortest_paths(gb_graph) -> NDArrayFloat:
    shortest_paths: NDArrayFloat = np.zeros(gb_graph.shape)


# print(floyd_warshall(graph.todense()))

"M_12"     nvals  nrows  ncols  dtype         format
gb.Matrix      6      5      5  INT64  bitmapr (iso)


TypeError: 'MatrixExpression' object is not callable

In [21]:
from graphblas import op, semiring, Matrix, Vector

# Create the graph and starting vector
start_node = 0
G = Matrix.from_coo(
    [0, 0, 1, 1, 2],
    [1, 2, 2, 3, 3],
    [2.0, 5.0, 1.5, 4.25, 0.5],
    nrows=4, ncols=4)
v = Vector.from_coo([start_node], [0.0], size=4)

# Compute SSSP
while True:
    w = v.dup()

    # Perform a BFS step using min_plus semiring
    # Accumulate into v using the `min` function
    v(op.min) << semiring.min_plus(v @ G)
    print(v.to_coo())
    # The algorithm is converged once v stops changing
    if v.isequal(w):
        break


(array([0, 1, 2], dtype=uint64), array([0., 2., 5.]))
(array([0, 1, 2, 3], dtype=uint64), array([0. , 2. , 3.5, 5.5]))
(array([0, 1, 2, 3], dtype=uint64), array([0. , 2. , 3.5, 4. ]))
(array([0, 1, 2, 3], dtype=uint64), array([0. , 2. , 3.5, 4. ]))
